version: "3.8"
services: 
    nginx_test:
        image: nginx:alpine
        container_name: nginx_test
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./test:/etc/nginx/html/test
        ports:
            - 8080:8080
        restart: always
